### ISSUE TITLE
The SSH command responded with a non-zero exit status

### ISSUE THREAD

**Issue by smth** [michaelck/puppet-lamp-stack-for-omeka#3]
Following the instructions in the readme, after `vagrant up` I get:
```
The SSH command responded with a non-zero exit status. Vagrant assumes that this means the command failed. The output for this command should be in the log above. Please read the output to determine what went wrong.
```
I'm guessing the crucial output is 
```
err: /Stage[main]/Php::Pear/Exec[pear install -a -f phpunit/PHPUnit]/returns: change from notrun to 0 failed: pear install -a -f phpunit/PHPUnit returned 1 instead of one of [0] at /tmp/vagrant-puppet/modules-d01bcbf07241502aa3c5cfdb68018e45/php/manifests/pear.pp:44
```

**Comment by triplingual** [comment]
+1 (Apologies if +1 posts are contrary to GitHub protocol — I'm still new around here.)

**Comment by michaelck** [comment]
@smth @triplingual Apologies for the long overdue response to this issue! I appreciate the issue submissions, but somehow managed to miss the notifications.

I've had a chance to dig into it and found that it was due to PHPUnit ending their support for the PEAR installation method. I'm testing a fix now and will commit shortly.
